### ISSUE TITLE
Mocha Testing API missing :(

### ISSUE THREAD

**Issue by kristianmandrup** [jmeas/es6-node-boilerplate#11]
For some reason most of Mocha seems disabled or WTF is going on?
Using `mocha 2.1.0`

Getting undefined when trying to use:
- `xdescribe`
- `xit`
- `describe.skip`
- ...

I can see only a few globals are listed in:

``` json
  "nodeBoilerplateOptions": {
    "mochaGlobals": [
      "stub",
      "spy",
      "expect"
    ]
  }
```

Then there is the `test/setup` folder where all kinds of other globals are defined. 
How to I configure this to get a normal mocha API???

Please HELP!

**Comment by kristianmandrup** [comment]
My mistake. Was an error due to wrong use of expectation syntax for testing `undefined` ...

**Comment by jamesplease** [comment]
:stuck_out_tongue:
